### REGISTER
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "firstName": "Marko",
  "lastName": "Markovic",
  "email": "marko@gmail.com",
  "password": "12345"
}

### LOGIN
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "zile028@gmail.com",
  "password": "12345"
}
