### 
GET http://localhost:4000/api/user

###
POST http://localhost:4000/api/user/add
Content-Type: application/json

{
  "firstName": "Dejan",
  "lastName": "Zivkovic"
}

###
PUT http://localhost:4000/api/user/update/545/dejan?age=38&pat=dog
Content-Type: application/json

{
  "firstName": "Dejan",
  "lastName": "Zivkovic"
}