### GET ALL USER
GET http://localhost:4000/api/user

###
POST http://localhost:4000/api/user/add
Content-Type: application/json

{
  "firstName": "Zdravko",
  "lastName": "Ristic"
}

###

PUT http://localhost:4000/api/user/update/6475ed5823cb3ed04c9208e8
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDc1ZWQ1ODIzY2IzZWQwNGM5MjA4ZTgiLCJmaXJzdE5hbWUiOiJaZHJhdmtvIiwibGFzdE5hbWUiOiJSaXN0aWMiLCJyb2xlIjoidXNlciIsInRpbWUiOjE2ODU0NTAxMjk0MDksImlhdCI6MTY4NTQ1MDEyOSwiZXhwIjoxNjg1NTM2NTI5fQ.sZvMUR-6FDBW3gq-FloYkrV4BHSqjNSlSgmBh-Usw8c
  

  {
  "firstName": "Zdravko"
  }