### GET ALL USER
GET http://localhost:4000/api/user

###
POST http://localhost:4000/api/user/add
Content-Type: application/json

{
  "firstName": "Dejan",
  "lastName": "Zivkovic"
}

###
PUT http://localhost:4000/api/user/update/644a553656f68374bf796481
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDZlNTE0ZTQ2MTFkYzJiZGRkYjdiN2EiLCJmaXJzdE5hbWUiOiJEZWphbiIsImxhc3ROYW1lIjoiWml2a292aWMiLCJyb2xlIjoiYWRtaW4iLCJ0aW1lIjoxNjg1NzI1NDc0MjU3LCJpYXQiOjE2ODU3MjU0NzQsImV4cCI6MTY4NTgxMTg3NH0.qZrEIBOy5vj6SrTeSQurQUHALTU1nFrVwGJn2YueqCM

{
  "firstName": "John"
}


### GET SINGE USER

GET http://localhost:4000/api/user/644a553656f68374bf796481